name: Benefactor Clairvoyant

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.415
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      #run: dotnet build --no-restore
      uses: ./.github/Action
      #run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish
    - name: Upload Coding Dojos Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CodingDojos
        path: /home/runner/work/OneClickDevOps/OneClickDevOps/OneClickDevOpsGithub/bin/Debug/netcoreapp3.1/publish/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      
